version: '3.0'

services:
  main:
    container_name: main
    build:
      context: .
    env_file:
      - .env
    volumes:
        - .:/server
        - /server/node_modules
    ports:
      - 3000:3000
      - 9229:9229
    command: npm run dev
    dependens_on:
      - postgres
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    .env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5433:5433
    volumes:
      - pgdata: var/lib/postgresql/data
    restart: always

volumes:
  pgdata: 
